import {useState} from 'react';
import {AlertTriangle,CheckCircle2,FileSpreadsheet,Upload,Download,RefreshCw} from 'lucide-react';
import {api,type ImportPreview} from './api';

type Kind='certifications'|'schedules';
const labels={certifications:{title:'자격증 기본 정보',template:'CERTIFICATION' as const,help:'자격증명 기준으로 신규·변경·동일 여부를 판정합니다.'},schedules:{title:'시험 일정',template:'SCHEDULE' as const,help:'자격증·회차·일정 유형 조합으로 중복을 판정합니다.'}};
function ImportPanel({kind}:{kind:Kind}){
 const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState<ImportPreview|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const info=labels[kind];
 const validate=async()=>{if(!file)return;setBusy(true);setMessage('');try{setPreview(await api.validateImport(kind,file));}catch(e){setMessage('오류: '+(e instanceof Error?e.message:'검증에 실패했습니다.'));setPreview(null);}finally{setBusy(false)}};
 const commit=async()=>{if(!preview?.canCommit)return;setBusy(true);try{const r=await api.commitImport(preview.token);setMessage(`반영 완료: 신규 ${r.created}건, 변경 ${r.updated}건, 동일 ${r.unchanged}건`);setPreview(null);setFile(null);}catch(e){setMessage('오류: '+(e instanceof Error?e.message:'반영에 실패했습니다.'));}finally{setBusy(false)}};
const download=async()=>{setBusy(true);setMessage('');try{await api.downloadTemplate(info.template);setMessage('CSV 양식을 다운로드했습니다.');}catch(e){setMessage('오류: '+(e instanceof Error?e.message:'템플릿을 내려받지 못했습니다.'));}finally{setBusy(false)}};
 return <section className="import-panel"><div className="import-head"><div><FileSpreadsheet/><div><h2>{info.title} CSV</h2><p>{info.help}</p></div></div><button className="secondary" onClick={download} disabled={busy}><Download size={15}/>양식 받기</button></div><div className="upload-row"><label className="file-input"><Upload/><span>{file?file.name:'UTF-8 CSV 파일 선택'}</span><input type="file" accept=".csv,text/csv" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null);setMessage('')}}/></label><button className="primary" disabled={!file||busy} onClick={validate}>{busy?<RefreshCw className="spin"/>:'업로드 전 검증'}</button></div>{message&&<div className={'import-message '+(message.startsWith('오류:')?'error':'')}>{message}</div>}{preview&&<><div className="import-summary"><span>전체 <strong>{preview.totalRows}</strong></span><span className="create">신규 <strong>{preview.createCount}</strong></span><span className="update">변경 <strong>{preview.updateCount}</strong></span><span>동일 <strong>{preview.unchangedCount}</strong></span><span className={preview.errorRows?'error':''}>오류 <strong>{preview.errorRows}</strong></span></div><div className="preview-table"><table><thead><tr><th>행</th><th>식별값</th><th>판정</th><th>변경/오류 내용</th><th>검수 상태</th><th>마지막 확인일</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.rowNumber} className={row.action==='ERROR'?'row-error':''}><td>{row.rowNumber}</td><td><strong>{row.key}</strong></td><td><span className={'action '+row.action.toLowerCase()}>{row.action}</span></td><td>{row.errors.length?row.errors.map((e,i)=><div className="field-error" key={i}>{e.field}: {e.message}</div>):row.changedFields.length?row.changedFields.join(', '):'변경 없음'}</td><td>{row.values.reviewStatus}</td><td>{row.values.lastVerifiedAt}</td></tr>)}</tbody></table></div><div className="commit-bar"><div>{preview.canCommit?<><CheckCircle2/>모든 행이 유효합니다. 검토 후 반영하세요.</>:<><AlertTriangle/>오류 행을 수정한 CSV로 다시 검증해야 합니다.</>}</div><button className="primary" disabled={!preview.canCommit||busy} onClick={commit}>검증 결과 반영</button></div></>}</section>
}
export default function AdminImport(){return <div className="page"><div className="page-title"><p className="eyebrow">ADMIN · DATA IMPORT</p><h1>운영 데이터 일괄 등록</h1><p>공식 출처가 확인된 자격증과 시험 일정을 검증한 뒤 반영합니다.</p></div><div className="notice"><AlertTriangle size={17}/><span><strong>공개 원칙</strong> 실제 데이터이며 검수 상태가 VERIFIED인 항목만 일반 사용자 화면에 공개됩니다.</span></div><ImportPanel kind="certifications"/><ImportPanel kind="schedules"/></div>}