import type {Certification,JobRole,Schedule} from './types';
const names=['백엔드 개발','프론트엔드 개발','데이터 엔지니어','AI 개발','클라우드·DevOps','정보보안','네트워크','QA·테스트'];
export const jobs:JobRole[]=names.map((name,id)=>({id:id+1,name,description:`${name} 직무와 연결되는 자격증을 확인합니다.`}));
const raw=[
['정보처리기사','소프트웨어 개발 전반의 기초 역량을 점검하는 국가기술자격','소프트웨어','NATIONAL','중급',12,'백엔드 개발'],['SQLD','데이터 모델링과 SQL 활용 역량을 검증하는 자격','데이터베이스','PRIVATE','입문',6,'데이터 엔지니어'],['SQLP','고급 데이터 모델링과 SQL 튜닝 역량을 검증하는 자격','데이터베이스','PRIVATE','심화',16,'데이터 엔지니어'],['ADsP','데이터 분석 기획과 기초 분석 역량을 다루는 자격','데이터·AI','PRIVATE','입문',5,'AI 개발'],['빅데이터분석기사','빅데이터 분석 기획부터 결과 해석까지 평가하는 국가기술자격','데이터·AI','NATIONAL','중급',14,'데이터 엔지니어'],['리눅스마스터','리눅스 운영과 관리 역량을 확인하는 자격','인프라','PRIVATE','입문',7,'클라우드·DevOps'],['네트워크관리사','네트워크 구축과 운용 능력을 평가하는 자격','네트워크','PRIVATE','중급',8,'네트워크'],['정보보안기사','정보보호 시스템과 관리 역량을 검증하는 국가기술자격','보안','NATIONAL','심화',18,'정보보안'],['AWS Solutions Architect Associate','AWS 기반 분산 시스템 설계 역량을 검증하는 벤더 자격','클라우드','VENDOR','중급',10,'클라우드·DevOps'],['AWS Developer Associate','AWS 애플리케이션 개발과 배포 역량을 검증하는 벤더 자격','클라우드','VENDOR','중급',9,'백엔드 개발'],['CKA','Kubernetes 클러스터 운영 능력을 실기로 검증하는 벤더 자격','클라우드','VENDOR','심화',12,'클라우드·DevOps'],['CCNA','네트워크 기초와 Cisco 장비 운용 역량을 검증하는 벤더 자격','네트워크','VENDOR','중급',12,'네트워크'],['ISTQB','소프트웨어 테스팅 원칙과 실무 지식을 검증하는 국제 자격','테스트','VENDOR','입문',6,'QA·테스트']];
const iso=(days:number)=>new Date(Date.now()+days*86400000).toISOString();
export const certifications:Certification[]=raw.map((x,i)=>({id:i+1,name:String(x[0]),summary:String(x[1]),category:String(x[2]),type:String(x[3]),organization:i>7?String(x[0]).split(' ')[0]:'주관 기관 확인 필요',difficulty:String(x[4]),preparationWeeks:Number(x[5]),recommendedJobs:[String(x[6])],sampleData:true,nextSchedule:{id:i+1,certificationId:i+1,certificationName:String(x[0]),title:i%3===0?'데모 접수 마감':'데모 시험일',type:i%3===0?'REGISTRATION_CLOSE':'EXAM',startsAt:iso(5+i*4),sampleData:true}}));
export const schedules:Schedule[]=certifications.map(c=>c.nextSchedule!);
export const typeLabel:Record<string,string>={NATIONAL:'국가자격',PRIVATE:'민간자격',VENDOR:'벤더자격',REGISTRATION_OPEN:'접수 시작',REGISTRATION_CLOSE:'접수 마감',EXAM:'시험일',RESULT:'발표일',RENEWAL:'갱신일'};
export const statuses=[['INTERESTED','관심 있음'],['PLANNED','준비 예정'],['STUDYING','공부 중'],['REGISTERED','접수 완료'],['TAKEN','응시 완료'],['PASSED','취득 완료'],['FAILED','불합격']];
